# /ansible/playbooks/task6_1.yml
---
- hosts: 1.1.1.1
  become: yes

  roles:
    - users
    - http


# /ansible/playbooks/task6_2.yml
---
- hosts: 1.1.1.1
  become: yes

  roles:
    - users
    - php
